/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package morning_bakery;

import java.awt.Color;
import java.awt.BasicStroke;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Hendra Huang
 */
public class login extends javax.swing.JFrame {

    private boolean passwordVisible = false;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        configureLoginView();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        brandTitleLabel = new javax.swing.JLabel();
        brandDescriptionLabel = new javax.swing.JLabel();
        brandFooterLabel = new javax.swing.JLabel();
        decorationPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        showPasswordButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SwiftBite - Login");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(83, 48, 31));
        mainPanel.setPreferredSize(new java.awt.Dimension(1100, 620));

        cardPanel.setBackground(new java.awt.Color(250, 247, 241));
        cardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 222, 205)));

        leftPanel.setBackground(new java.awt.Color(117, 70, 43));

        logoPanel.setBackground(new java.awt.Color(248, 248, 248));

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(190, 102, 45));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("S");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        brandTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 39)); // NOI18N
        brandTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        brandTitleLabel.setText("SwiftBite");

        brandDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        brandDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        brandDescriptionLabel.setText("<html>Platform kasir dan pemesanan digital<br>restoran.</html>");

        brandFooterLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        brandFooterLabel.setForeground(new java.awt.Color(255, 255, 255));
        brandFooterLabel.setText("QR table ordering system");

        decorationPanel.setBackground(new java.awt.Color(117, 70, 43));
        decorationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(166, 125, 96)));

        javax.swing.GroupLayout decorationPanelLayout = new javax.swing.GroupLayout(decorationPanel);
        decorationPanel.setLayout(decorationPanelLayout);
        decorationPanelLayout.setHorizontalGroup(
            decorationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        decorationPanelLayout.setVerticalGroup(
            decorationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandFooterLabel)
                    .addComponent(brandDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(decorationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(brandTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(decorationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(brandFooterLabel)
                .addGap(29, 29, 29))
        );

        rightPanel.setBackground(new java.awt.Color(250, 247, 241));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(24, 19, 23));
        titleLabel.setText("Masuk akun");

        subtitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(126, 78, 46));
        subtitleLabel.setText("Masuk untuk mulai mengelola pesanan.");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(24, 19, 23));
        usernameLabel.setText("Username");

        usernameTextField.setBackground(new java.awt.Color(250, 247, 241));
        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 171, 125)));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(24, 19, 23));
        passwordLabel.setText("Password");

        passwordField.setBackground(new java.awt.Color(250, 247, 241));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 171, 125)));

        showPasswordButton.setBackground(new java.awt.Color(250, 247, 241));
        showPasswordButton.setForeground(new java.awt.Color(126, 78, 46));
        showPasswordButton.setText("show");
        showPasswordButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 171, 125)));
        showPasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswordButton.setFocusPainted(false);
        showPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButtonActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(105, 59, 35));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Masuk");
        loginButton.setBorder(null);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel)
                    .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(showPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addGap(35, 35, 35)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureLoginView() {
        loadLogo();

        getRootPane().setDefaultButton(loginButton);
        passwordField.setEchoChar('\u2022');

        Color normalBorder = new Color(220, 171, 125);
        Color focusBorder = new Color(126, 78, 46);
        installFieldBorder(usernameTextField, normalBorder, focusBorder);

        decorationPanel.setOpaque(false);
        decorationPanel.setBorder(new DiamondBorder(new Color(185, 145, 116, 170)));

        Border passwordNormalBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 1, 1, 0, normalBorder),
                BorderFactory.createEmptyBorder(0, 12, 0, 8));
        Border passwordFocusBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 1, 1, 0, focusBorder),
                BorderFactory.createEmptyBorder(0, 12, 0, 8));
        passwordField.setBorder(passwordNormalBorder);
        passwordField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent event) {
                passwordField.setBorder(passwordFocusBorder);
                showPasswordButton.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 1, focusBorder));
            }

            @Override
            public void focusLost(FocusEvent event) {
                passwordField.setBorder(passwordNormalBorder);
                showPasswordButton.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 1, normalBorder));
            }
        });

        showPasswordButton.setText("");
        showPasswordButton.setIcon(new EyeIcon(false));
        showPasswordButton.setContentAreaFilled(false);
        showPasswordButton.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 1, normalBorder));
        showPasswordButton.setToolTipText("Tampilkan password");
        showPasswordButton.getAccessibleContext().setAccessibleName("Tampilkan password");

        Color buttonNormal = new Color(105, 59, 35);
        Color buttonHover = new Color(126, 78, 46);
        loginButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent event) {
                loginButton.setBackground(buttonHover);
            }

            @Override
            public void mouseExited(MouseEvent event) {
                loginButton.setBackground(buttonNormal);
            }
        });
    }

    private void installFieldBorder(javax.swing.JTextField field, Color normalColor, Color focusColor) {
        Border normalBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(normalColor),
                BorderFactory.createEmptyBorder(0, 12, 0, 12));
        Border focusBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(focusColor),
                BorderFactory.createEmptyBorder(0, 12, 0, 12));
        field.setBorder(normalBorder);
        field.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent event) {
                field.setBorder(focusBorder);
            }

            @Override
            public void focusLost(FocusEvent event) {
                field.setBorder(normalBorder);
            }
        });
    }

    private void loadLogo() {
        URL logoUrl = getClass().getResource("/morning_bakery/assets/Swiftbite.png");
        if (logoUrl == null) {
            System.err.println("Logo SwiftBite tidak ditemukan di folder assets.");
            return;
        }

        ImageIcon icon = new ImageIcon(logoUrl);
        Image scaledImage = icon.getImage().getScaledInstance(46, 46, Image.SCALE_SMOOTH);
        logoLabel.setText("");
        logoLabel.setIcon(new ImageIcon(scaledImage));
        setIconImage(icon.getImage());
    }

    private static final class EyeIcon implements Icon {

        private final boolean crossed;

        private EyeIcon(boolean crossed) {
            this.crossed = crossed;
        }

        @Override
        public int getIconWidth() {
            return 20;
        }

        @Override
        public int getIconHeight() {
            return 20;
        }

        @Override
        public void paintIcon(Component component, Graphics graphics, int x, int y) {
            Graphics2D g2 = (Graphics2D) graphics.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(126, 78, 46));
            g2.setStroke(new BasicStroke(1.8f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            g2.drawOval(x + 2, y + 6, 16, 9);
            g2.fillOval(x + 8, y + 9, 4, 4);
            if (crossed) {
                g2.drawLine(x + 3, y + 3, x + 17, y + 17);
            }
            g2.dispose();
        }
    }

    private static final class DiamondBorder implements Border {

        private final Color color;

        private DiamondBorder(Color color) {
            this.color = color;
        }

        @Override
        public Insets getBorderInsets(Component component) {
            return new Insets(2, 2, 2, 2);
        }

        @Override
        public boolean isBorderOpaque() {
            return false;
        }

        @Override
        public void paintBorder(Component component, Graphics graphics, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) graphics.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(color);
            g2.setStroke(new BasicStroke(1.2f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));

            int centerX = x + (width / 2);
            int centerY = y + (height / 2);
            int[] xPoints = {centerX, x + width - 2, centerX, x + 1};
            int[] yPoints = {y + 1, centerY, y + height - 2, centerY};
            g2.drawPolygon(xPoints, yPoints, 4);
            g2.dispose();
        }
    }

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameTextField.getText().trim();
        String password = new String(passwordField.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan password wajib diisi.");
            return;
        }

        new DashboardKasir(2L, username).setVisible(true);
        dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void showPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButtonActionPerformed
        passwordVisible = !passwordVisible;
        passwordField.setEchoChar(passwordVisible ? (char) 0 : '\u2022');
        showPasswordButton.setIcon(new EyeIcon(passwordVisible));
        showPasswordButton.setToolTipText(passwordVisible ? "Sembunyikan password" : "Tampilkan password");
        showPasswordButton.getAccessibleContext().setAccessibleName(
                passwordVisible ? "Sembunyikan password" : "Tampilkan password");
    }//GEN-LAST:event_showPasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandDescriptionLabel;
    private javax.swing.JLabel brandFooterLabel;
    private javax.swing.JLabel brandTitleLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel decorationPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton showPasswordButton;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
